@api = http://localhost:3000/respuesta

GET {{api}}/solicitudes 

###
GET {{api}}/eventos 

###
GET {{api}}/solicitudes/12

###
GET {{api}}/eventos/1

###
GET {{api}}/solicitudes/count

###
GET {{api}}/eventos/count

###
POST {{api}}/solicitud
Content-Type: application/json

{
  "id_solicitud": null,
  "rut_postulante": "14.222.313-3",
  "codigo_actividad": 1,
  "fecha_inscripcion": "2021-12-01",
  "datos_extra": "Nueva solicitud",
  "obs_medica": "ninguna observacion"
}

###
POST {{api}}/evento
Content-Type: application/json

{
  "codigo_actividad": 4,
  "rut_responsable": "13.231.412-2",
  "tipo": "Taller",
  "cupos": 10,
  "direccion": "Av. Cubo Rubik 123",
  "nombre_actividad": "Futbol",
  "estado_actividad": "Postulando",
  "descripción": "Esta actividad se realiza con todos los clubes deportivos de quintero",
  "fecha_inicio": "2022-03-03",
  "fecha_termino": "2022-04-04",
  "modalidad": "Presencial",
  "requisitos": "Tener zapatos de fútbol",
  "area": "Futbol"
}

###
DELETE {{api}}/solicitud/14

###
PUT {{api}}/solicitud/6
Content-Type: application/json

{
  "datos_extra": "actualize esto :V"
}