@api = http://10.100.6.6:3000/respuesta

GET {{api}}/solicitudes 

###
GET {{api}}/eventos 

###
GET {{api}}/solicitud/13.231.412-2

###
GET {{api}}/eventos/1

###
GET {{api}}/solicitudes/count

###
GET {{api}}/eventos/count

###
POST {{api}}/solicitud
Content-Type: application/json

{
  "id_solicitud": null,
  "rut_postulante": "14.222.313-3",
  "codigo_actividad": 1,
  "fecha_inscripcion": "2021-12-01",
  "datos_extra": "Nueva solicitud",
  "obs_medica": "ninguna observacion"
}

###
POST {{api}}/evento
Content-Type: application/json

{
  "codigo_actividad": null,
  "rut_responsable": "13.231.412-2",
  "tipo": "Evento",
  "cupos": 11,
  "direccion": "Av. Cubo Rubik 123",
  "nombre_actividad": "Natacion",
  "estado_actividad": "Postulando",
  "descripción": "Este Evento en el club de Quintero",
  "fecha_inicio": "2022-03-03",
  "fecha_termino": "2022-04-04",
  "modalidad": "Presencial",
  "requisitos": "Tener gorro de natación",
  "area": "Natacion"
}


###
POST {{api}}/evento
Content-Type: application/json

{
  "codigo_actividad": null,
  "rut_responsable": "13.231.412-2",
  "tipo": "Evento",
  "cupos": 12,
  "direccion": "Av. Cubo Rubik 123",
  "nombre_actividad": "Futbol",
  "estado_actividad": "Postulando",
  "descripción": "Este Evento en la cancha de Quintero",
  "fecha_inicio": "2022-10-10",
  "fecha_termino": "2022-10-10",
  "modalidad": "Presencial",
  "requisitos": "Zapato de futbol",
  "area": "Futbol"
}

###
POST {{api}}/evento
Content-Type: application/json

{
  "codigo_actividad": null,
  "rut_responsable": "13.231.412-2",
  "tipo": "Evento",
  "cupos": 10,
  "direccion": "Av. Cubo Rubik 123",
  "nombre_actividad": "Basquetbol",
  "estado_actividad": "Postulando",
  "descripción": "Este Evento en la cancha de Basquetbol Quintero",
  "fecha_inicio": "2022-10-10",
  "fecha_termino": "2022-10-10",
  "modalidad": "Presencial",
  "requisitos": "Zapato de Basquetbol",
  "area": "Basquetbol"
}

###
POST {{api}}/evento
Content-Type: application/json

{
  "codigo_actividad": null,
  "rut_responsable": "13.231.412-2",
  "tipo": "Evento",
  "cupos": 40,
  "direccion": "Av. Cubo Rubik 123",
  "nombre_actividad": "Maraton",
  "estado_actividad": "Postulando",
  "descripción": "Este Evento en la plaza de Quintero",
  "fecha_inicio": "2022-10-10",
  "fecha_termino": "2022-10-10",
  "modalidad": "Presencial",
  "requisitos": "Zapato de Maraton",
  "area": "Maraton"
}

###
POST {{api}}/evento
Content-Type: application/json

{
  "codigo_actividad": null,
  "rut_responsable": "13.231.412-2",
  "tipo": "Evento",
  "cupos": 6,
  "direccion": "Av. Cubo Rubik 123",
  "nombre_actividad": "Tenis",
  "estado_actividad": "Postulando",
  "descripción": "Este Evento en la cancha de tenis de Quintero",
  "fecha_inicio": "2022-10-10",
  "fecha_termino": "2022-10-10",
  "modalidad": "Presencial",
  "requisitos": "Zapato de Tenis",
  "area": "Tenis"
}
###
DELETE {{api}}/solicitud/14

###
DELETE {{api}}/evento/1


###
PUT {{api}}/solicitud/6
Content-Type: application/json

{
  "datos_extra": "actualize esto :V"
}

###
PUT {{api}}/evento/8
Content-Type: application/json

{
  "nombre_actividad": "Natación"
}